### PR TITLE
Added a new getGroupGames function

### PR DESCRIPTION
**Pull request by Vilksian**
I noticed there wasn't any convenient way to get the games owned by a group, so I made a function for it.

### CODE REVIEW

**Comment by popeeyy** [comment]
getGroupGames should be using [this](https://github.com/suufi/noblox.js/blob/master/lib/util/getPageResults.js) function as it uses cursors. There is an example of this [here](https://github.com/suufi/noblox.js/blob/master/lib/user/getInventory.js).

**Comment by Vilksian** [comment]
> getGroupGames should be using [this](https://github.com/suufi/noblox.js/blob/master/lib/util/getPageResults.js) function as it uses cursors. There is an example of this [here](https://github.com/suufi/noblox.js/blob/master/lib/user/getInventory.js).

Thanks. Changed the function to work with that.

**Review by Neztore — CHANGES_REQUESTED** [review]
Please squash your commit, i.e. removing changes that are already on master.

Thanks!

**Comment by Vilksian** [comment]
> Please squash your commit, i.e. removing changes that are already on master.
> 
> Thanks!

I'm not sure what you mean by that. What parts are already in the master branch?

**Comment by suufi** [comment]
Closed by #345

**Pull request closed without merging**
