### PR TITLE
Added getGameRevenue

### PR DESCRIPTION
**Pull request by GoldenJayz**
This just gets the game revenue. This was not in noblox.js before so I added it in.

### CODE REVIEW

**Comment by suufi** [comment]
I can't approve this because it's missing return type and typings. See other functions for examples.

**Comment by Neztore** [comment]
Could you lint this so it passes the CI?

**Review by Neztore — CHANGES_REQUESTED** [review]
See above: Please pass CI

**Review by GoldenJayz — COMMENTED** [review]
I just linted this. Ty :)

**Review by Neztore — CHANGES_REQUESTED** [review]
Please add typings to [index.d.ts](https://github.com/noblox/noblox.js/blob/master/typings/index.d.ts) and [jsdocs](https://github.com/noblox/noblox.js/blob/master/typings/jsDocs.ts) as required. Thanks for linting!

**Review by GoldenJayz — COMMENTED** [review]
Added typings

**Comment by GoldenJayz** [comment]
@Neztore

**Review by GoldenJayz — COMMENTED** [review]
@Neztore @suufi 👀

**Comment by Neztore** [comment]
Hm. Odd. Never got any emails for this one. I'll review now

**Review by Neztore — APPROVED** [review]

**Pull request merged**
