### PR TITLE
Fix addDeveloperProducts & getDeveloperProducts

### PR DESCRIPTION
**Pull request by Noxirity**
Removed the initial check to see if the name is available, as `checkDeveloperProductName` is throwing a "You are not logged in" error due to the check-developerproduct-name endpoint no longer existing.

`Product with this name already exists` will still be thrown if that is the case
I also marked checkDeveloperProductName as deprecated

Updated getDeveloperProducts to use the new correct endpoint

My first PR so sorry if im doing anything wrong 😝

### CODE REVIEW

**Comment by Noxirity** [comment]
fixed that publishToTopic formatting because it was a bit messed up

**Comment by luluwaffless** [comment]
why was this closed? its exactly the fix that i need and was about to work on LOL, you should reopen this
image

**Comment by frrazer** [comment]
> why was this closed? its exactly the fix that i need and was about to work on LOL, you should reopen this image

i dont actually remember why i closed this sorry! 😩
does the code from this PR still work? i can reopen it if everything still works, i dont have time to check it myself right now

**Comment by luluwaffless** [comment]
> i dont actually remember why i closed this sorry! 😩 does the code from this PR still work? i can reopen it if everything still works, i dont have time to check it myself right now

seems to work just fine, but the API im trying to use to get developer products is `//apis.roblox.com/developer-products/v2/universes/${universeId}/developerproducts` which doesn't require authentication for public games and already responds with all product information
the one the code uses is `//apis.roblox.com/developer-products/v1/universes/${universeId}/developerproducts` and `//apis.roblox.com/developer-products/v1/developer-products/${product.id}`, which DOES require authentication
some rewriting should do the deal, don't worry about it if you're not interested tho!

**Pull request closed without merging**
