### PR TITLE
Add Get Dev Forum Info method

### PR DESCRIPTION
**Pull request by Conmmander**
getDevForumInfo.mjs

This commit focus's on adding dev forum functionality to this module, a much-needed feature for some, and relevant

### CODE REVIEW

**Comment by conman0552** [comment]
Please let me know if I missed any doc updates. Hopefully, I got it all!

**Comment by conman0552** [comment]
I believe typings have been added properly now. Again, feel free to let me know if I may have missed any.

**Review by alanbixby — CHANGES_REQUESTED** [review]
Didn't look too closely at the typings; fix the function name and it'd be shippable- better error handling (i.e stating the status code of an unknown error) is only a plus.

**Comment by conman0552** [comment]
@alanbixby Thank you for the feedback. I've gone through and made most of the changes. I'm inclined to agree with you on error handling, though I may ask for your help in implementing that. 

I think someone more qualified should work with devforum authentication, so I am going to leave that alone for now.

**Pull request closed without merging**
