### PR TITLE
Switch userinfo endpoint

### PR DESCRIPTION
**Pull request by Regalijan**
Given it's a www endpoint, there is a not-insignificant chance that Roblox will remove it in the near future (and we're heading towards v5 anyways)

### CODE REVIEW

**Comment by alanbixby** [comment]
Please make a new method; `getAuthenticatedUser` then that utilizes the new endpoint.

We can fix this issue without introducing a breaking change per #809

**Comment by Regalijan** [comment]
Hi yes it is done

**Review by Neztore — CHANGES_REQUESTED** [review]
`yarn run lint` fails (push to topic?)

**Comment by Regalijan** [comment]
> `yarn run lint` fails (push to topic?)

Yeah this was fixed after the pr was opened

**Comment by Neztore** [comment]
> > `yarn run lint` fails (push to topic?)
> 
> Yeah this was fixed after the pr was opened

Huh. I just cloned the repo and ran lint. Will have another look

**Pull request merged**
