### PR TITLE
Fix addDeveloperProduct

### PR DESCRIPTION
**Pull request by TomerJ**
Changed to use another endpoint, as the previous one was returning a 404 error.

### CODE REVIEW

**Review by Coquelicots — APPROVED** [review]

**Comment by Coquelicots** [comment]
Same on updateDeveloperProduct, the endpoint is //apis.roblox.com/developer-products/v1/universes/${universeId}/developerproducts/${productId}/update

**Comment by FernandoPelarich** [comment]
Is this fixed already? When I try to require the module and use the function it doesnt work

**Review by FernandoPelarich — CHANGES_REQUESTED** [review]
Here this says that has been changed, but when I require the module in a .js file the function addDeveloperProduct doesn't work

**Review by FernandoPelarich — APPROVED** [review]

**Review by FernandoPelarich — APPROVED** [review]

**Comment by FernandoPelarich** [comment]
image

**Comment by FernandoPelarich** [comment]
Apparently this error is fixed, but when I try to use Noblox in glitch.com with this function I keep getting the same exact error 404. Also in the main page when I go to the source file code for addDeveloperProduct there are no changes 
image

**Review by UntakerAnonPLAY — APPROVED** [review]

**Review by BillyH-0167 — APPROVED** [review]

**Review by Neztore — APPROVED** [review]

**Pull request merged**
